### ISSUE TITLE
Tree construction with early edits anchored

### ISSUE THREAD

**Issue by mysecretbackyard** [mckennalab/TreeUtils#2]
Hi, 
Thank you for a great analysis tool. I tried to do a tree construction with a subset of my data and found out the pipeline doesn't anchor the tree with early edits. Basically, I have barcodes that share similar edits at site 5-9 but differ in site 1-4 on the same clade. Is there a way to do it so that I have early edits followed by late edits on the tree? 
![image](https://user-images.githubusercontent.com/51543050/158495340-5bc7770f-3cb9-4a02-ab5f-8b4f986cde37.png)

Thank you.
Thitinee

**Comment by aaronmck** [comment]
Hi Thitinee,

Sorry for the slow response here. I know the documentation is non-existent, but have you tried --subsetFirstX to limit edits to the first X tagets in initial tree creation (for instant --subsetFirstX 4)?

**Comment by mysecretbackyard** [comment]
Hi Aaron,

Just tried it and it now works beautifully. Thank you!

Thitinee

**Comment by aaronmck** [comment]
Great!
